server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://REAL_HOST:REAL_PORT/REAL_DB
spring.datasource.username=REAL_USER
spring.datasource.password=REAL_PASSWORD

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect